# Generated by Django 5.0.6 on 2024-09-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
