# Generated by Django 5.0.6 on 2024-10-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_alter_cartitem_sizes_alter_cartitem_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_slip",
            field=models.ImageField(blank=True, null=True, upload_to="payment_slips/"),
        ),
    ]
