# Generated by Django 5.0.6 on 2024-10-29 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_payment_payment_slip"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="sizes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.size",
            ),
        ),
    ]
